name: Update README with Recent Activity

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch Recent Activity
        uses: varunsridharan/github-activity-readme@v1.0.1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: KrshnK
          MAX_LINES: 5

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README with recent activity
          branch: main
          file_pattern: README.md
